--------------------------------------------------------
--  File created - Wednesday-Julay-31-2019   
--------------------------------------------------------
DROP TABLE "HR"."CVS" cascade constraints;
DROP TABLE "HR"."MEMBERS" cascade constraints;
--------------------------------------------------------
--  Sequence CVS_CV_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."CVS_CV_SEQ"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  CVS
--------------------------------------------------------

  CREATE TABLE "HR"."CVS" 
   (	"CV_ID" NUMBER(8,0), 
	"MAIN_SKILL" VARCHAR2(200 BYTE), 
	"WORK_EXPERIENCE" VARCHAR2(4000 BYTE), 
	"EDUCATION" VARCHAR2(500 BYTE), 
	"MEMBER_ID" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--   MEMBERS
--------------------------------------------------------

  CREATE TABLE "HR"."MEMBERS" 
   (	"MEMBER_ID" NUMBER(8,0), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(40 BYTE), 
	"EMAIL" VARCHAR2(60 BYTE), 
	"UNAME" VARCHAR2(20 BYTE), 
	"PASS" VARCHAR2(20 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"ROLE" VARCHAR2(20 BYTE) DEFAULT 'CANDIDATE'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.CVS
SET DEFINE OFF;
Insert into HR.CVS (CV_ID,MAIN_SKILL,WORK_EXPERIENCE,EDUCATION,MEMBER_ID) values (1,'AAA','Job1','CV11111111111111111111111111111111111111111111111','EDUCATION1',10);
Insert into HR.CVS (CV_ID,MAIN_SKILL,WORK_EXPERIENCE,EDUCATION,MEMBER_ID) values (2,'BBB','Job2','CV22222222222222222222222222222222222222222222222','EDUCATION2',20);
Insert into HR.CVS (CV_ID,MAIN_SKILL,WORK_EXPERIENCE,EDUCATION,MEMBER_ID) values (3,'CCC','Job3','CV33333333333333333333333333333333333333333333333','EDUCATION3',30);
--------------------------------------------------------
--   Index CVS_CV_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."CVS_CV_ID_PK" ON "HR"."CVS" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--   Trigger CVS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."CVS_TRG" 
BEFORE INSERT ON CVS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CV_ID IS NULL THEN
      SELECT CVS_CV_SEQ.NEXTVAL INTO :NEW.CV_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HR"."CVS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table CVS
--------------------------------------------------------

  ALTER TABLE "HR"."CVS" ADD CONSTRAINT "CVS_CV_ID_PK" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."CVS" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CVS
--------------------------------------------------------

  ALTER TABLE "HR"."CVS" ADD CONSTRAINT "CVS_FK1" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "HR"."MEMBERS" ("MEMBER_ID") ENABLE;

--------------------------------------------------------
--  JOBS
--------------------------------------------------------

  CREATE TABLE "HR"."JOBS" 
   (	"EMPLOYER_ID" NUMBER(8,0), 
	"TITLE" VARCHAR2(200 BYTE), 
	"DESCRIP" VARCHAR2(4000 BYTE), 
	"SALARY" NUMBER(10,2), 
	"REQUIRED_SKILL" VARCHAR2(500 BYTE), 
	"CO_DESCRPTION" VARCHAR2(4000 BYTE), 
	"CITY" VARCHAR2(25 BYTE), 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"END_DATE" DATE DEFAULT SYSDATE+20, 
	"MEMBER_ID" NUMBER(8,0), 
	"TYPE" VARCHAR2(20 BYTE), 
	"COMPANY_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  MEMBERS
--------------------------------------------------------

  CREATE TABLE "HR"."MEMBERS" 
   (	"MEMBER_ID" NUMBER(8,0), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(40 BYTE), 
	"EMAIL" VARCHAR2(60 BYTE), 
	"UNAME" VARCHAR2(20 BYTE), 
	"PASS" VARCHAR2(20 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"ROLE" VARCHAR2(20 BYTE) DEFAULT 'CANDIDATE'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.JOBS
SET DEFINE OFF;
Insert into HR.JOBS (EMPLOYER_ID,TITLE,DESCRIP,SALARY,REQUIRED_SKILL,CO_DESCRPTION,CITY,CREATION_DATE,END_DATE,MEMBER_ID,TYPE,COMPANY_NAME) values (1111,'AAAA','JOB1',11,'Offer1','Offer11','aaaa',to_date('19-07-11','RR-MM-DD'),to_date('19-07-10','RR-MM-DD'),11,'Inter','AA');
Insert into HR.JOBS (EMPLOYER_ID,TITLE,DESCRIP,SALARY,REQUIRED_SKILL,CO_DESCRPTION,CITY,CREATION_DATE,END_DATE,MEMBER_ID,TYPE,COMPANY_NAME) values (2222,'BBBB','JOB2',22,'Offer2','Offer22','bbbb',to_date('19-07-22','RR-MM-DD'),to_date('19-07-12','RR-MM-DD'),22,'Perman','BB');
Insert into HR.JOBS (EMPLOYER_ID,TITLE,DESCRIP,SALARY,REQUIRED_SKILL,CO_DESCRPTION,CITY,CREATION_DATE,END_DATE,MEMBER_ID,TYPE,COMPANY_NAME) values (3333,'CCCC','JOB3',33,'Offer3','Offer33','cccc',to_date('19-07-24','RR-MM-DD'),to_date('19-07-20','RR-MM-DD'),33,'Contr','CC');
--------------------------------------------------------
--  Index JOBS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."JOBS_PK" ON "HR"."JOBS" ("EMPLOYER_ID", "TITLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--   Trigger JOBS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."JOBS_TRG" 
BEFORE INSERT ON JOBS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HR"."JOBS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table JOBS
--------------------------------------------------------

  ALTER TABLE "HR"."JOBS" ADD CONSTRAINT "JOBS_PK" PRIMARY KEY ("EMPLOYER_ID", "TITLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."JOBS" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."JOBS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."JOBS" MODIFY ("EMPLOYER_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."JOBS" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."JOBS" MODIFY ("TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table JOBS
--------------------------------------------------------

  ALTER TABLE "HR"."JOBS" ADD CONSTRAINT "JOBS_MEMBERS_FK1" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "HR"."MEMBERS" ("MEMBER_ID") ENABLE;

--------------------------------------------------------
--    MEMBERS
--------------------------------------------------------

  CREATE TABLE "HR"."MEMBERS" 
   (	"MEMBER_ID" NUMBER(8,0), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(40 BYTE), 
	"EMAIL" VARCHAR2(60 BYTE), 
	"UNAME" VARCHAR2(20 BYTE), 
	"PASS" VARCHAR2(20 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"ROLE" VARCHAR2(20 BYTE) DEFAULT 'CANDIDATE'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.MEMBERS
SET DEFINE OFF;
Insert into HR.MEMBERS (MEMBER_ID,FIRST_NAME,LAST_NAME,EMAIL,UNAME,PASS,REGDATE,ROLE) values (11,'A','AA','AAA@gmail.com','AAAA','AAAAA',to_date('19-06-10','RR-MM-DD'),'COMPANY');
Insert into HR.MEMBERS (MEMBER_ID,FIRST_NAME,LAST_NAME,EMAIL,UNAME,PASS,REGDATE,ROLE) values (22,'B','BB','BBB@gmail.com','BBBB','BBBBB',to_date('19-06-11','RR-MM-DD'),'CANDIDATE');
Insert into HR.MEMBERS (MEMBER_ID,FIRST_NAME,LAST_NAME,EMAIL,UNAME,PASS,REGDATE,ROLE) values (33,'C','CC','CCC@gmail.com','CCCC','CCCCC',to_date('19-06-12','RR-MM-DD'),'CANDIDATE');
Insert into HR.MEMBERS (MEMBER_ID,FIRST_NAME,LAST_NAME,EMAIL,UNAME,PASS,REGDATE,ROLE) values (44,'D','DD','DDD@gmail.com','DDDD','DDDD',to_date('19-06-13','RR-MM-DD'),'COMPANY');
Insert into HR.MEMBERS (MEMBER_ID,FIRST_NAME,LAST_NAME,EMAIL,UNAME,PASS,REGDATE,ROLE) values (55,'E','EE','EEE@gmail.com','EEEE','EEEE',to_date('19-06-14','RR-MM-DD'),'CANDIDATE');
Insert into HR.MEMBERS (MEMBER_ID,FIRST_NAME,LAST_NAME,EMAIL,UNAME,PASS,REGDATE,ROLE) values (66,'F','FF','FFF@gmail.com','FFFF','FFFF',to_date('19-06-15','RR-MM-DD'),'CANDIDATE');
Insert into HR.MEMBERS (MEMBER_ID,FIRST_NAME,LAST_NAME,EMAIL,UNAME,PASS,REGDATE,ROLE) values (77,'G','GG','GGG@gmail.com','GGGG','GGGG',to_date('19-06-16','RR-MM-DD'),'COMPANY');
Insert into HR.MEMBERS (MEMBER_ID,FIRST_NAME,LAST_NAME,EMAIL,UNAME,PASS,REGDATE,ROLE) values (88,'H','HH','HHH@gmail.com','HHHH','HHHH',to_date('19-06-17','RR-MM-DD'),'CANDIDATE');
Insert into HR.MEMBERS (MEMBER_ID,FIRST_NAME,LAST_NAME,EMAIL,UNAME,PASS,REGDATE,ROLE) values (99,'I','II','III@gmail.com','IIII','IIII',to_date('19-06-18','RR-MM-DD'),'COMPANY');
Insert into HR.MEMBERS (MEMBER_ID,FIRST_NAME,LAST_NAME,EMAIL,UNAME,PASS,REGDATE,ROLE) values (100,'J','JJ','JJJ@gmail.com','JJJJ','JJJJ',to_date('19-06-19','RR-MM-DD'),'COMPANY');
Insert into HR.MEMBERS (MEMBER_ID,FIRST_NAME,LAST_NAME,EMAIL,UNAME,PASS,REGDATE,ROLE) values (200,'K','KK','KKK@gmail.com','KKKK','KKKK',to_date('19-06-20','RR-MM-DD'),'CANDIDATE');
Insert into HR.MEMBERS (MEMBER_ID,FIRST_NAME,LAST_NAME,EMAIL,UNAME,PASS,REGDATE,ROLE) values (300,'M','MM','MMM@gmail.com','MMMM','MMMM',to_date('19-06-21','RR-MM-DD'),'CANDIDATE');
Insert into HR.MEMBERS (MEMBER_ID,FIRST_NAME,LAST_NAME,EMAIL,UNAME,PASS,REGDATE,ROLE) values (400,'N','NN','NNN@gmail.com','NNNN','NNNN',to_date('19-06-22','RR-MM-DD'),'CANDIDATE');
--------------------------------------------------------
--  Index MEMBERS_MEMBER_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."MEMBERS_MEMBER_ID_PK" ON "HR"."MEMBERS" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index MEMBERS_EMAIL_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."MEMBERS_EMAIL_UK" ON "HR"."MEMBERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index MEMBERS_USER_NAME_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."MEMBERS_USER_NAME_UK" ON "HR"."MEMBERS" ("UNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--   Trigger MEMBERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."MEMBERS_TRG" 
BEFORE INSERT ON MEMBERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HR"."MEMBERS_TRG" ENABLE;
--------------------------------------------------------
--   Trigger MEMBERS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."MEMBERS_TRG1" 
BEFORE INSERT ON MEMBERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HR"."MEMBERS_TRG1" ENABLE;
--------------------------------------------------------
--   Trigger MEMBERS_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."MEMBERS_TRG2" 
BEFORE INSERT ON MEMBERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.MEMBER_ID IS NULL THEN
      SELECT MEMBERS_SEQ2.NEXTVAL INTO :NEW.MEMBER_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HR"."MEMBERS_TRG2" ENABLE;
--------------------------------------------------------
--  Table MEMBERS
--------------------------------------------------------

  ALTER TABLE "HR"."MEMBERS" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERS" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERS" MODIFY ("UNAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERS" ADD CONSTRAINT "MEMBERS_USER_NAME_UK" UNIQUE ("UNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."MEMBERS" ADD CONSTRAINT "MEMBERS_EMAIL_UK" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."MEMBERS" ADD CONSTRAINT "MEMBERS_MEMBER_ID_PK" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."MEMBERS" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);


